<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  el7:
    roles:
      - default
      - el7
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>
    yum_repos:
      chef-current:
        baseurl: 'https://packages.chef.io/repos/yum/current/el/7/$basearch'
        gpgkeys:
          - https://packages.chef.io/chef.asc
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch'
        gpgkeys:
          - https://getfedora.org/static/352C64E5.txt

CONFIG:
  log_level: verbose
  type:      aio
  vagrant_memsize: 256
<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% end -%>
