---
HOSTS:
  el7:
    roles:
    - default
    - el7
    platform: el-7-x86_64
    box: centos/7
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    yum_repos:
      chef-current:
        baseurl: https://packages.chef.io/repos/yum/current/el/7/$basearch
        gpgkeys:
        - https://packages.chef.io/chef.asc
      epel:
        mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
        gpgkeys:
        - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    family: centos-cloud/centos-7
    gce_machine_type: n1-standard-2
CONFIG:
  log_level: verbose
  type: aio
  puppet_collection: "<%= ENV.fetch('BEAKER_PUPPET_COLLECTION', 'puppet7') %>"
