---
fixtures:
  repositories:
    auditd:                "https://github.com/simp/pupmod-simp-auditd"
    augeasproviders_core:  "https://github.com/simp/augeasproviders_core"
    augeasproviders_grub:  "https://github.com/simp/augeasproviders_grub"
    concat:                "https://github.com/simp/puppetlabs-concat"
    inifile:               "https://github.com/simp/puppetlabs-inifile"
    gnome:                 "https://github.com/simp/pupmod-simp-gnome"
    logrotate:             "https://github.com/simp/pupmod-simp-logrotate"
    pki:                   "https://github.com/simp/pupmod-simp-pki"
    polkit:                "https://github.com/simp/pupmod-simp-polkit"
    rsyslog:               "https://github.com/simp/pupmod-simp-rsyslog"
    simpcat:               "https://github.com/simp/pupmod-simp-simpcat"
    simplib:               "https://github.com/simp/pupmod-simp-simplib"
    stdlib:                "https://github.com/simp/puppetlabs-stdlib"
  symlinks:
    gdm: "#{source_dir}"
