---
fixtures:
  repositories:
    concat: https://github.com/simp/puppetlabs-concat
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup
    dconf: https://github.com/simp/pupmod-simp-dconf
    inifile: https://github.com/simp/puppetlabs-inifile
    polkit: https://github.com/simp/pupmod-simp-polkit
    simplib:
      repo: https://github.com/trevor-vaughan/pupmod-simp-simplib
      branch: SIMP-4654
    stdlib: https://github.com/simp/puppetlabs-stdlib
    svckill: https://github.com/simp/pupmod-simp-svckill

    # Fixtures needed for acceptance
    gnome: https://github.com/simp/pupmod-simp-gnome
  symlinks:
    gdm: "#{source_dir}"
