---
fixtures:
  repositories:
    concat: https://github.com/simp/puppetlabs-concat
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup
    dconf: https://github.com/simp/pupmod-simp-dconf
    inifile: https://github.com/simp/puppetlabs-inifile
    polkit: https://github.com/simp/pupmod-simp-polkit
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
    svckill: https://github.com/simp/pupmod-simp-svckill
    simp_banners: https://github.com/simp/pupmod-simp-simp_banners

    # For compliance testing
    disa_stig-el7-baseline:
      repo: https://github.com/simp/inspec-profile-disa_stig-el7
      branch:  master
      target: spec/fixtures/inspec_deps/inspec_profiles/profiles

    # Fixtures needed for acceptance
    gnome: https://github.com/simp/pupmod-simp-gnome
  symlinks:
    gdm: "#{source_dir}"
